# Generated by Django 5.2.1 on 2025-06-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_buku', models.CharField(default='0000', max_length=10, unique=True)),
                ('kode_buku', models.CharField(default='0000', max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(blank=True, max_length=100, null=True)),
                ('stok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal_dibuat', models.DateField(blank=True, null=True)),
                ('jenis', models.CharField(max_length=100)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nomor_anggota', models.CharField(max_length=100, unique=True)),
                ('kode_verifikasi', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Belum Kembali', 'Belum Kembali'), ('Kembali', 'Kembali')], max_length=20)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengunjung')),
            ],
        ),
        migrations.CreateModel(
            name='NotifikasiBerhasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.CharField(max_length=255)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengunjung')),
            ],
        ),
        migrations.CreateModel(
            name='KembalikanBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kembali', models.DateField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengunjung')),
            ],
        ),
        migrations.CreateModel(
            name='GagalPinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengunjung')),
            ],
        ),
        migrations.CreateModel(
            name='PinjamBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('dikembalikan', 'Dikembalikan'), ('gagal', 'Gagal')], max_length=20)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengunjung')),
            ],
        ),
    ]
