# Generated by Django 5.2.1 on 2025-05-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
                ('jenis', models.CharField(max_length=100)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nomor_anggota', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GagalPinjam',
            fields=[
                ('id_buku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perpustakaan.kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KembalikanBuku',
            fields=[
                ('id_buku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perpustakaan.kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifikasiBerhasil',
            fields=[
                ('id_buku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perpustakaan.kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinjamBuku',
            fields=[
                ('id_buku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perpustakaan.kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('dikembalikan', 'Dikembalikan'), ('gagal', 'Gagal')], max_length=20)),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengunjung')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pinjambuku')),
            ],
        ),
    ]
