# Generated by Django 5.2.1 on 2025-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kode_buku',
            new_name='id_buku',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='penulis',
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_dibuat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
