# Generated by Django 5.2.1 on 2025-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='nomor_anggota',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
