# Generated by Django 5.2.1 on 2025-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='id',
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='buku',
            name='kode_buku',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
