# Generated by Django 5.2.1 on 2025-05-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_alter_pengunjung_nomor_anggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengunjung',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pengunjung',
            name='kode_verifikasi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
